#!/bin/sh
echo "installing sox for ogg play"
which play > /dev/null || apt-get install sox

echo "setup timezone to KST"
cp -f /usr/share/zoneinfo/ROK /etc/localtime

echo "generate config.json for test"
./tools/mkconfig > config.json

echo "generate and install schedule.json for test"
./tools/mkschedule > /var/www/work/schedule.json

INIT_D_ENABLE=""
INIT_D_DISABLE="lightdm xrdp" #avahi-daemon

for S in $INIT_D_ENABLE
do
 echo "enable $S"
 update-rc.d "$S" defaults
 /etc/init.d/$S start
done

for S in $INIT_D_DISABLE
do
 echo "disable $S"
 update-rc.d -f "$S" remove
 /etc/init.d/$S stop
done
