#!/usr/bin/env python2
import json
import os
import time

HOST="http://localhost:8080/work/"

items = (
 ('10:10:00', '1.mp3'),
 ('11:10:00', '2.mp3'),
 ('13:40:00', '3.mp3'),
 ('14:25:00', '4.mp3'),
 ('15:10:00', '5.mp3'),
)

def item(x):
    return {'scheduled': x[0], 'url': os.path.join(HOST, x[1])}

c = {'created': time.time(),
'items': [ item(x) for x in items]
}

print json.dumps(c)

